### ISSUE TITLE
Fixed versions makes the build to fail

### ISSUE THREAD

**Issue by danielgomezrico** [la-haus/iterable-flutter#15]
If I have in my pubspec versions like this:
```YAML
environment:
  sdk: 2.14.2
  flutter: 2.5.1
```

Then `flutter pub get` fails with:
```dart
The current Dart SDK version is 2.14.2.
Because client depends on iterable_flutter from git which requires SDK version 2.13.3, version solving failed.
pub get failed (1; Because client depends on iterable_flutter from git which requires SDK version 2.13.3, version solving failed.)
```

This happens because the library have the dart version fixed and so the clients should use the same one, but that will cause that they can not update their flutter or dart versions.

# Ideas

Should we se the dart version variable in the library `pubspec.yml`?

```YAML
environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: 2.2.2
```
